name: publish Borderless Gaming


on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
            fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish -c ${{ matrix.configuration }} -r win-x64

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: Borderless-Gaming (${{ matrix.configuration }})
          path: |
            .\BorderlessGaming\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\publish\*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Get short version of commit hash
        run: |
          echo "shortcommithash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Download x64 release artifact
        uses: actions/download-artifact@main
        with:
          name: Borderless-Gaming (Release)
          path: x64-Release

      - name: Download x64 debug artifact
        uses: actions/download-artifact@main
        with:
          name: Borderless-Gaming (Debug)
          path: x64-Debug

      - name: Rename artifacts
        run: |
          mv x64-Release/BorderlessGaming.exe BorderlessGaming-${{ env.shortcommithash }}-Release.exe
          mv x64-Debug/BorderlessGaming.exe BorderlessGaming-${{ env.shortcommithash }}-Debug.exe

      - name: Delete old release
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          draft: false
          make_latest: true
          files: |
            BorderlessGaming-${{ env.shortcommithash }}.exe
          name: Build ${{ env.shortcommithash }}
          tag_name: ${{ env.shortcommithash }}
          generate_release_notes: true