name: publish Borderless Gaming


on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
            fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -r win-x64

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: installer
          path: |
            ./Installers/BorderlessGaming${{ env.RELEASE_VERSION }}_admin_setup.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Get short version of commit hash
        run: |
          echo "shortcommithash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Download x64 artifact
        uses: actions/download-artifact@main
        with:
          name: installer
          path: Release

      - name: Rename artifacts
        run: |
          mv Release/BorderlessGaming${{ env.RELEASE_VERSION }}_admin_setup.exe BorderlessGaming-${{ env.shortcommithash }}.exe

      - name: Delete old release
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          draft: false
          make_latest: true
          files: |
            BorderlessGaming-${{ env.shortcommithash }}.exe
          name: Build ${{ env.shortcommithash }}
          tag_name: ${{ env.shortcommithash }}
          generate_release_notes: true